version: 2

models:
  - name: dim_account
    description: Account dimension

    config:
      contract:
        enforced: true

    columns:
      - name: account_key
        data_type: string
        tests: [not_null, unique]

      - name: account_code
        data_type: string
        tests: [not_null]

      - name: account_currency_code
        data_type: string
        tests: [not_null]


  - name: dim_security
    description: Security dimension

    config:
      contract:
        enforced: true

    columns:
      - name: security_key
        data_type: string
        tests: [not_null, unique]

      - name: security_code
        data_type: string
        tests: [not_null]

      - name: security_name
        data_type: string
        tests: [not_null]

      - name: sector_name
        data_type: string

      - name: industry_name
        data_type: string

      - name: country_code
        data_type: string

      - name: exchange_code
        data_type: string


  - name: dim_exchange
    description: Exchange dimension

    config:
      contract:
        enforced: true

    columns:
      - name: exchange_key
        data_type: string
        tests: [not_null, unique]

      - name: exchange_code
        data_type: string
        tests: [not_null]

      - name: exchange_name
        data_type: string
        tests: [not_null]

      - name: country_name
        data_type: string

      - name: city_name
        data_type: string

      - name: timezone_name
        data_type: string

      - name: tz_delta_hours
        data_type: number(38,0)

      - name: dst_period_desc
        data_type: string

      - name: open_local
        data_type: string

      - name: close_local
        data_type: string

      - name: lunch_local
        data_type: string

      - name: open_utc
        data_type: string

      - name: close_utc
        data_type: string

      - name: lunch_utc
        data_type: string


  - name: dim_currency
    description: Currency dimension

    config:
      contract:
        enforced: true

    columns:
      - name: currency_key
        data_type: string
        tests: [not_null, unique]

      - name: currency_code
        data_type: string
        tests: [not_null]

      - name: currency_num_code
        data_type: number(38,0)

      - name: decimal_digits
        data_type: number(38,0)

      - name: currency_name
        data_type: string
        tests: [not_null]

      - name: locations
        data_type: string


  - name: dim_country
    description: Country dimension

    config:
      contract:
        enforced: true

    columns:
      - name: country_key
        data_type: string
        tests: [not_null, unique]

      - name: country_code
        data_type: string
        tests: [not_null]

      - name: country_name
        data_type: string
        tests: [not_null]

      - name: region
        data_type: string

      - name: sub_region
        data_type: string

      - name: iso_code
        data_type: string


  - name: fact_position
    description: Positions by account, security, exchange, currency, and report_date

    config:
      contract:
        enforced: true

    tests:
      - dbt_utils.unique_combination_of_columns:
          name: fact_position_unique_combo
          combination_of_columns:
            - account_key
            - security_key
            - exchange_key
            - currency_key
            - report_date

    columns:
      - name: account_key
        data_type: string
        tests:
          - not_null
          - relationships:
              to: ref('dim_account')
              field: account_key

      - name: security_key
        data_type: string
        tests:
          - not_null
          - relationships:
              to: ref('dim_security')
              field: security_key

      - name: exchange_key
        data_type: string
        tests:
          - not_null
          - relationships:
              to: ref('dim_exchange')
              field: exchange_key

      - name: currency_key
        data_type: string
        tests:
          - not_null
          - relationships:
              to: ref('dim_currency')
              field: currency_key

      - name: report_date
        data_type: date
        tests: [not_null]

      - name: quantity
        data_type: number(38,0)

      - name: cost_base
        data_type: number(38,2)

      - name: position_value
        data_type: number(38,2)

      - name: unrealized_profit
        data_type: number(38,2)

      - name: unrealized_profit_pct
        data_type: number(38,5)
