name: 'ledgerline'
version: '1.0.0'
config-version: 2

profile: 'ledgerline'  # dbt Cloud ignores this for jobs/IDE

model-paths: ['models']
analysis-paths: ['analyses']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

target-path: 'target'
clean-targets:
  - 'target'
  - 'dbt_packages'

vars:
  stg_materialization: 'ephemeral'

quoting:
  database: false
  schema: false
  identifier: false

models:
  ledgerline:
    +persist_docs: {relation: true, columns: true}

    staging:
      +schema: staging
      +materialized: "{{ var('stg_materialization', 'ephemeral') }}"

    history:
      +schema: history
      +materialized: incremental
      +incremental_strategy: append
      +on_schema_change: append_new_columns

    refined:
      +schema: refined
      +materialized: table

    marts:
      +materialized: table

      # disable the old finance mart if that folder still exists
      portfolio:
        +enabled: false

      # new SaaS usage mart
      usage:
        +schema: marts_usage
        +contract: {enforced: true}

seeds:
  +schema: seeds

  ledgerline:
    +quote_columns: false

    customers:
      +column_types:
        customer_code: varchar
        customer_name: varchar
        country_code: varchar
        load_ts: timestamp_ntz
      +post-hook:
        - "update {{ this }} set load_ts = to_timestamp_ntz('{{ run_started_at }}') where load_ts is null"

    products:
      +column_types:
        product_code: varchar
        product_name: varchar
        category: varchar
        load_ts: timestamp_ntz
      +post-hook:
        - "update {{ this }} set load_ts = to_timestamp_ntz('{{ run_started_at }}') where load_ts is null"

    plans:
      +column_types:
        plan_code: varchar
        plan_name: varchar
        product_code: varchar
        billing_period: varchar
        load_ts: timestamp_ntz
      +post-hook:
        - "update {{ this }} set load_ts = to_timestamp_ntz('{{ run_started_at }}') where load_ts is null"

    currencies:
      +column_types:
        currency_code: varchar
        currency_name: varchar
        decimal_digits: number
        load_ts: timestamp_ntz
      +post-hook:
        - "update {{ this }} set load_ts = to_timestamp_ntz('{{ run_started_at }}') where load_ts is null"

    countries:
      +column_types:
        country_code: varchar
        country_name: varchar
        load_ts: timestamp_ntz
      +post-hook:
        - "update {{ this }} set load_ts = to_timestamp_ntz('{{ run_started_at }}') where load_ts is null"

    price_book_daily:
      +column_types:
        product_code: varchar
        plan_code: varchar
        price_date: date
        unit_price: number
        load_ts: timestamp_ntz
      +post-hook:
        - "update {{ this }} set load_ts = to_timestamp_ntz('{{ run_started_at }}') where load_ts is null"

    usage_daily:
      +column_types:
        customer_code: varchar
        product_code: varchar
        plan_code: varchar
        report_date: date
        units_used: number
        included_units: number
        load_ts: timestamp_ntz
      +post-hook:
        - "update {{ this }} set load_ts = to_timestamp_ntz('{{ run_started_at }}') where load_ts is null"