name: 'marginsync'
version: '1.0.0'
config-version: 2

profile: 'marginsync'  # dbt Cloud ignores this value for jobs/IDE

model-paths: ['models']
analysis-paths: ['analyses']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

target-path: 'target'
clean-targets:
  - 'target'
  - 'dbt_packages'

models:
  market_sync_dbt:
    +persist_docs: {relation: true, columns: true}

    # Views so we can see them in Snowflake
    staging:
      +schema: staging
      +materialized: "{{ var('stg_materialization', 'view') }}"

    history:
      +schema: history
      +materialized: incremental
      +incremental_strategy: append
      +on_schema_change: append_new_columns

    refined:
      +schema: refined
      +materialized: table

    marts:
      +materialized: table
      portfolio:
        +schema: marts_portfolio
        +materialized: table
        +contract: {enforced: true}


seeds:
  +schema: seeds
  market_sync_dbt:
    +quote_columns: false

    abc_bank_security_info:
      +column_types:
        LOAD_TS: timestamp
      +post-hook:
        - "update {{ this }} set LOAD_TS = to_timestamp('{{ run_started_at }}') where LOAD_TS is null"

    abc_bank_country_info:
      +column_types:
        LOAD_TS: timestamp
      +post-hook:
        - "update {{ this }} set LOAD_TS = to_timestamp('{{ run_started_at }}') where LOAD_TS is null"

    abc_bank_currency_info:
      +column_types:
        LOAD_TS: timestamp
      +post-hook:
        - "update {{ this }} set LOAD_TS = to_timestamp('{{ run_started_at }}') where LOAD_TS is null"

    abc_bank_exchange_info:
      +column_types:
        LOAD_TS: timestamp
      +post-hook:
        - "update {{ this }} set LOAD_TS = to_timestamp('{{ run_started_at }}') where LOAD_TS is null"

    abc_bank_account_info:
      +column_types:
        LOAD_TS: timestamp_ntz
      +post-hook:
        - "update {{ this }} set LOAD_TS = to_timestamp_ntz('{{ run_started_at }}') where LOAD_TS is null"

snapshots:
  +schema: 'history'