version: 2

models:
  - name: STG_ABC_BANK_POSITION
    tests:
      - dbt_utils.expression_is_true:
          arguments:
            expression: "extract(year from report_date) >= 2000"
          config:
            severity: warn
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - account_code
              - security_code
              - exchange_code
              - currency_code
              - report_date