version: 2

models:
  - name: STG_ABC_BANK_POSITION
    tests:
      - dbt_utils.expression_is_true:
          expression: "year(report_date) >= 2000"

  - name: HIST_ABC_BANK_POSITION
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - POSITION_HKEY
            - LOAD_TS_UTC

    columns:
      - name: POSITION_HKEY
        tests:
          - hash_collision_free:
              hashed_fields:
                - ACCOUNT_CODE
                - SECURITY_CODE

      - name: POSITION_HDIFF
        tests:
          - hash_collision_free:
              hashed_fields:
                - ACCOUNT_CODE
                - SECURITY_CODE
                - SECURITY_NAME
                - EXCHANGE_CODE
                - "to_varchar(REPORT_DATE, 'YYYY-MM-DD')"
                - QUANTITY
                - COST_BASE
                - POSITION_VALUE
                - CURRENCY_CODE
