# staging.yml
# ---------------------------------------------------------------------------
# Schema definitions for the Staging layer.
#
# Staging adapts raw sources/seeds into normalized, deduplicated tables.
# It enforces uniqueness, adds defaults, and prepares clean inputs for history.
#
# Note: staging models expose an ingestion_ts column (rename from load_ts).
# ---------------------------------------------------------------------------

version: 2

models:

  # ----------------------------------------------------------------------
  # stg_atlas_meter_usage_daily
  # ----------------------------------------------------------------------
  # Staging table for daily metered usage feed.
  # - Year must be >= 2000
  # - One row per (customer_code, product_code, plan_code, report_date)
  # ----------------------------------------------------------------------

  - name: stg_atlas_meter_usage_daily

    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns: [customer_code, product_code, plan_code, report_date]

      - dbt_utils.expression_is_true:
          name: report_date_year_gte_2000
          arguments:
            expression: "extract(year from report_date) >= 2000"

    columns:
      - name: customer_code
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('atlas_crm_customer_info')
                field: customer_code
                where: "customer_code <> '-1'"

      - name: product_code
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('atlas_catalog_product_info')
                field: product_code
                where: "product_code <> '-1'"

      - name: plan_code
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('atlas_catalog_plan_info')
                field: plan_code
                where: "plan_code <> '-1'"

      - name: report_date
        tests: [not_null]

      - name: units_used
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0

      - name: included_units
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0

      - name: ingestion_ts
        tests: [not_null]

  # ----------------------------------------------------------------------
  # stg_atlas_price_book_daily
  # ----------------------------------------------------------------------
  # Staging table for daily price book feed.
  # - Year must be >= 2000
  # - One row per (product_code, plan_code, price_date)
  # ----------------------------------------------------------------------

  - name: stg_atlas_price_book_daily

    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns: [product_code, plan_code, price_date]

      - dbt_utils.expression_is_true:
          name: price_date_year_gte_2000
          arguments:
            expression: "extract(year from price_date) >= 2000"

    columns:
      - name: product_code
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('atlas_catalog_product_info')
                field: product_code
                where: "product_code <> '-1'"

      - name: plan_code
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('atlas_catalog_plan_info')
                field: plan_code
                where: "plan_code <> '-1'"
      - name: price_date
        tests: [not_null]

      - name: unit_price
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
      - name: ingestion_ts
        tests: [not_null]

  # ----------------------------------------------------------------------
  # stg_atlas_crm_customer_info
  # ----------------------------------------------------------------------
  # Staging table for CRM customer info.
  # - customer_code must be unique and not null
  # ----------------------------------------------------------------------

  - name: stg_atlas_crm_customer_info

    columns:
      - name: customer_code
        tests: [unique, not_null]

      - name: customer_name
        tests: [not_null]

      - name: country_code
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('atlas_country_info')
                field: country_code
                where: "country_code <> '-1'"
      - name: ingestion_ts
        tests: [not_null]

  # ----------------------------------------------------------------------
  # stg_atlas_catalog_product_info
  # ----------------------------------------------------------------------
  # Staging table for product catalog info.
  # - product_code must be unique and not null
  # ----------------------------------------------------------------------

  - name: stg_atlas_catalog_product_info

    columns:
      - name: product_code
        tests: [unique, not_null]

      - name: product_name
        tests: [not_null]

      - name: ingestion_ts
        tests: [not_null]

  # ----------------------------------------------------------------------
  # stg_atlas_catalog_plan_info
  # ----------------------------------------------------------------------
  # Staging table for subscription plan catalog.
  # - plan_code must be unique and not null
  # ----------------------------------------------------------------------

  - name: stg_atlas_catalog_plan_info

    columns:
      - name: plan_code
        tests: [unique, not_null]

      - name: product_code
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('atlas_catalog_product_info')
                field: product_code
                where: "product_code <> '-1'"

      - name: billing_period
        tests:
          - accepted_values:
              values: ['monthly', 'annual']
              where: "plan_code <> '-1' and billing_period is not null"

      - name: ingestion_ts
        tests: [not_null]

  # ----------------------------------------------------------------------
  # stg_atlas_currency_info
  # ----------------------------------------------------------------------
  # Staging table for supported currencies.
  # - currency_code must be unique and not null
  # ----------------------------------------------------------------------

  - name: stg_atlas_currency_info

    columns:
      - name: currency_code
        tests: [unique, not_null]

      - name: currency_name
        tests: [not_null]

      - name: decimal_digits
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
          - dbt_utils.expression_is_true:
              arguments:
                expression: "= floor(decimal_digits)"
      - name: ingestion_ts
        tests: [not_null]

  # ----------------------------------------------------------------------
  # stg_atlas_country_info
  # ----------------------------------------------------------------------
  # Staging table for country reference data.
  # - country_code must be unique and not null
  # ----------------------------------------------------------------------

  - name: stg_atlas_country_info

    columns:
      - name: country_code
        tests: [unique, not_null]

      - name: country_name
        tests: [not_null]

      - name: ingestion_ts
        tests: [not_null]
