version: 2

models:
  - name: STG_ABC_BANK_POSITION
    tests:
      - dbt_utils.expression_is_true:
          expression: "extract(year from report_date) >= 2000"

  - name: HIST_ABC_BANK_POSITION
    tests:
      # One row per distinct version
      - unique:
          column_name: POSITION_HDIFF
      - not_null:
          column_name: POSITION_HDIFF

    columns:
      - name: POSITION_HKEY
        tests:
          - not_null
          - hash_collision_free:
              arguments:
                hashed_fields:
                  - ACCOUNT_CODE
                  - SECURITY_CODE

      - name: POSITION_HDIFF
        tests:
          - hash_collision_free:
              arguments:
                hashed_fields:
                  - ACCOUNT_CODE
                  - SECURITY_CODE
                  - SECURITY_NAME
                  - EXCHANGE_CODE
                  - "to_varchar(REPORT_DATE, 'YYYY-MM-DD')"
                  - QUANTITY
                  - COST_BASE
                  - POSITION_VALUE
                  - CURRENCY_CODE
