version: 2

models:
  - name: stg_atlas_meter_usage_daily
    tests:
      - dbt_utils.expression_is_true:
          expression: "extract(year from report_date) >= 2000"
          config: {severity: warn}

      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [customer_code, product_code, plan_code, report_date]



  - name: stg_atlas_pricing_rate_card_daily
    tests:
      - dbt_utils.expression_is_true:
          expression: "extract(year from price_date) >= 2000"
          config: {severity: warn}

      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [product_code, plan_code, price_date]



  - name: stg_atlas_crm_customer_info
    tests:
      - unique:
          column_name: customer_code
      - not_null:
          column_name: customer_code



  - name: stg_atlas_catalog_product_info
    tests:
      - unique:
          column_name: product_code
      - not_null:
          column_name: product_code



  - name: stg_atlas_catalog_plan_info
    tests:
      - unique:
          column_name: plan_code
      - not_null:
          column_name: plan_code



  - name: stg_atlas_ref_currency_info
    tests:
      - unique:
          column_name: currency_code
      - not_null:
          column_name: currency_code



  - name: stg_atlas_ref_country_info
    tests:
      - unique:
          column_name: country_code2
      - not_null:
          column_name: country_code2
